dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.2.0

compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.2.0"
dotenv: .env
networks:
  default: mainnet-fork
  ganache:
    verify: False
  mainnet-fork:
    verify: False
    fau_token: "0xFab46E002BbF0b4509813474841E0716E6730136"
  kovan:
    verify: True
    fau_token: "0xFab46E002BbF0b4509813474841E0716E6730136"
wallets:
  from_key: ${PRIVATE_KEY}
